plugins {
    id "com.android.application"
}

android {
    namespace "com.norahc.sleeptimer"
    compileSdk 35

    defaultConfig {
        applicationId "com.norahc.sleeptimer"
        minSdk 28
        targetSdk 35
        versionCode 10
        versionName "1.2.7"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
}
